# Generated by Django 6.1.2 on 2026-10-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(default='General Agent', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='required_role',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='interagentmessage',
            name='receiver_agent',
        ),
        migrations.RemoveField(
            model_name='interagentmessage',
            name='sender_agent',
        ),
        migrations.RemoveField(
            model_name='interagentmessage',
            name='task',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='api_url',
            field=models.URLField(default='http://localhost:11434', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='system_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='AgentRole',
        ),
        migrations.DeleteModel(
            name='ApiProvider',
        ),
        migrations.DeleteModel(
            name='InterAgentMessage',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
